/**
 * Auto-generated by sync-env.js from .env
 * DO NOT EDIT MANUALLY - Update .env and run: node sync-env.js
 */

const ENV_PROFILE = {
  "id": "shivansh_profile",
  "name": "Shivansh Nigam",
  "isDefault": true,
  "createdAt": "2026-09-17T22:09:44.628Z",
  "firstName": "Shivansh",
  "lastName": "Nigam",
  "fullName": "Shivansh Nigam",
  "email": "s2704nigam@gmail.com",
  "collegeEmail": "2311301214@stu.manit.ac.in",
  "phone": "7049949474",
  "phoneCountryCode": "+91",
  "dob": "27/04/2004",
  "gender": "Male",
  "preferredPronouns": "He/Him",
  "github": "https://github.com/Shivanshh27",
  "linkedin": "https://linkedin.com/in/shivanshh27",
  "twitter": "https://x.com/Shivanshh27",
  "portfolio": "https://github.com/Shivanshh27",
  "schoolName": "Maulana Azad National Institute of Technology (MANIT) Bhopal",
  "degreeLevel": "B.Tech",
  "degreeMajor": "Electrical Engineering",
  "rollNo": "2311301214",
  "graduationYear": "2027",
  "startYear": "2023",
  "gpa": "",
  "tenthPercentage": "84",
  "tenthYear": "2020",
  "twelfthPercentage": "76",
  "twelfthYear": "2022",
  "backlogs": "0",
  "addressLine1": "Maulana Azad National Institute of Technology Bhopal",
  "addressLine2": "",
  "city": "Bhopal",
  "state": "Madhya Pradesh",
  "postalCode": "462003",
  "country": "India",
  "relocate": "Yes",
  "currentTitle": "Software Developer",
  "currentCompany": "",
  "totalYearsExp": "0",
  "noticePeriodDays": "Immediate",
  "currentCTC": "6",
  "expectedCTC": "15",
  "authorizedInCountry": "Yes",
  "requireVisaSponsorship": "No",
  "usVeteranStatus": "I am not a protected veteran",
  "disabilityStatus": "No, I do not have a disability",
  "raceEthnicity": "Asian",
  "customFields": [
    {
      "key": "Branch",
      "value": "Electrical Engineering"
    },
    {
      "key": "GitHub",
      "value": "https://github.com/Shivanshh27"
    }
  ]
};

if (typeof self !== 'undefined') {
  self.ENV_PROFILE = ENV_PROFILE;
}
if (typeof window !== 'undefined') {
  window.ENV_PROFILE = ENV_PROFILE;
}
if (typeof module !== 'undefined') {
  module.exports = ENV_PROFILE;
}
