/**
 * Env Sync Script
 * Parses .env and writes config.js for the Chrome Extension
 */

const fs = require('fs');
const path = require('path');

const envPath = path.join(__dirname, '.env');
const samplePath = path.join(__dirname, 'env.sample');
const configPath = path.join(__dirname, 'config.js');

function parseEnv(filePath) {
  if (!fs.existsSync(filePath)) return {};
  const content = fs.readFileSync(filePath, 'utf8');
  const env = {};

  content.split(/\r?\n/).forEach(line => {
    line = line.trim();
    if (!line || line.startsWith('#')) return;

    const eqIdx = line.indexOf('=');
    if (eqIdx !== -1) {
      const key = line.substring(0, eqIdx).trim();
      let val = line.substring(eqIdx + 1).trim();
      if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
        val = val.slice(1, -1);
      }
      env[key] = val;
    }
  });

  return env;
}

const env = fs.existsSync(envPath) ? parseEnv(envPath) : parseEnv(samplePath);

const profileConfig = {
  id: 'shivansh_profile',
  name: env.FULL_NAME || 'Shivansh Nigam',
  isDefault: true,
  createdAt: new Date().toISOString(),

  firstName: env.FIRST_NAME || 'Shivansh',
  lastName: env.LAST_NAME || 'Nigam',
  fullName: env.FULL_NAME || 'Shivansh Nigam',
  email: env.EMAIL || 's2704nigam@gmail.com',
  collegeEmail: env.COLLEGE_EMAIL || env.EMAIL || 's2704nigam@gmail.com',
  phone: env.PHONE || '',
  phoneCountryCode: env.PHONE_COUNTRY_CODE || '+91',
  dob: env.DOB || '',
  gender: env.GENDER || 'Male',
  preferredPronouns: env.PREFERRED_PRONOUNS || 'He/Him',

  github: env.GITHUB_URL || 'https://github.com/Shivanshh27',
  linkedin: env.LINKEDIN_URL || 'https://linkedin.com/in/shivanshh27',
  twitter: env.TWITTER_URL || 'https://x.com/Shivanshh27',
  portfolio: env.PORTFOLIO_URL || 'https://github.com/Shivanshh27',

  schoolName: env.COLLEGE_NAME || 'Maulana Azad National Institute of Technology (MANIT) Bhopal',
  degreeLevel: env.DEGREE_LEVEL || 'B.Tech',
  degreeMajor: env.SPECIALIZATION || 'Electrical Engineering',
  rollNo: env.ROLL_NO || '',
  graduationYear: env.GRADUATION_YEAR || '2026',
  startYear: env.START_YEAR || '2022',
  gpa: env.GPA || '',
  tenthPercentage: env.TENTH_PERCENTAGE || '',
  tenthYear: env.TENTH_PASS_YEAR || '2020',
  twelfthPercentage: env.TWELFTH_PERCENTAGE || '',
  twelfthYear: env.TWELFTH_PASS_YEAR || '2022',
  backlogs: env.ACTIVE_BACKLOGS || '0',

  addressLine1: env.ADDRESS_LINE_1 || '',
  addressLine2: env.ADDRESS_LINE_2 || '',
  city: env.CITY || 'Bhopal',
  state: env.STATE || 'Madhya Pradesh',
  postalCode: env.POSTAL_CODE || '',
  country: env.COUNTRY || 'India',
  relocate: env.WILLING_TO_RELOCATE || 'Yes',

  currentTitle: env.CURRENT_TITLE || 'Software Developer',
  currentCompany: env.CURRENT_COMPANY || '',
  totalYearsExp: env.TOTAL_YEARS_EXP || '0',
  noticePeriodDays: env.NOTICE_PERIOD_DAYS || 'Immediate',
  currentCTC: env.CURRENT_CTC || '',
  expectedCTC: env.EXPECTED_CTC || '',

  authorizedInCountry: env.WORK_AUTHORIZATION || 'Yes',
  requireVisaSponsorship: env.REQUIRE_VISA_SPONSORSHIP || 'No',
  usVeteranStatus: env.US_VETERAN_STATUS || 'I am not a protected veteran',
  disabilityStatus: env.DISABILITY_STATUS || 'No, I do not have a disability',
  raceEthnicity: env.RACE_ETHNICITY || 'Asian',

  customFields: [
    { key: 'Branch', value: env.SPECIALIZATION || 'Electrical Engineering' },
    { key: 'GitHub', value: env.GITHUB_URL || 'https://github.com/Shivanshh27' }
  ]
};

const fileContent = `/**
 * Auto-generated by sync-env.js from .env
 * DO NOT EDIT MANUALLY - Update .env and run: node sync-env.js
 */

const ENV_PROFILE = ${JSON.stringify(profileConfig, null, 2)};

if (typeof self !== 'undefined') {
  self.ENV_PROFILE = ENV_PROFILE;
}
if (typeof window !== 'undefined') {
  window.ENV_PROFILE = ENV_PROFILE;
}
if (typeof module !== 'undefined') {
  module.exports = ENV_PROFILE;
}
`;

fs.writeFileSync(configPath, fileContent, 'utf8');
console.log('✅ Synchronized .env -> config.js successfully!');
